var Collection = [
    {
        No:1,
        describe:'您的年龄？',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'18—30',
                score:3
            },{
                desc:'31—50',
                score:2
            },{
                desc:'51—60',
                score:1
            },{
                desc:'高于60岁',
                score:0
            }
        ]
    },{
        No:2,
        describe:'您的职业？',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'公司职员',
                score:0
            },{
                desc:'事业单位',
                score:1
            },{
                desc:'创业主',
                score:2
            },{
                desc:'企业高管',
                score:3
            },{
                desc:'其他',
                score:4
            }
        ]
    },{
        No:3,
        describe:'您家庭的年收入？',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'10万元（含）以下',
                score:0
            },{
                desc:'10万至20万（含）',
                score:1
            },{
                desc:'20万至50万（含）',
                score:2
            },{
                desc:'50万以上',
                score:3
            }
        ]
    },{
        No:4,
        describe:'您预计家庭的年收入在未来5年中将？',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'有所下降',
                score:0
            },{
                desc:'维持稳定',
                score:1
            },{
                desc:'小幅成长，在10%左右',
                score:2
            },{
                desc:'大幅成长，在20%以上',
                score:3
            }
        ]
    },{
        No:5,
        describe:'在您每年的家庭收入中，可用于金融投资（储蓄存款除外）的比例为？',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'小于10%',
                score:0
            },{
                desc:'10%至25%',
                score:1
            },{
                desc:'25%至50%',
                score:2
            },{
                desc:'大于50%',
                score:3
            }
        ]
    },{
        No:6,
        describe:'以下哪项最能说明您的投资经验？',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'除存款、国债外，我几乎不投资其他金融产品',
                score:0
            },{
                desc:'大部分投资于存款、国债等，较少投资于股票、基金等风险产品',
                score:1
            },{
                desc:'资产均衡地分布于存款、国债、银行理财产品、信托产品、股票、基金等',
                score:2
            },{
                desc:'大部分投资于股票、基金、外汇等高风险产品，较少投资于存款、国债',
                score:3
            }
        ]
    },{
        No:7,
        describe:'您有多少年投资股票、基金、外汇、期货、金融衍生产品等风险投资品的经验',
        belong:{
            type:1,
            desc:'基本情况',
        },
        options:[
            {
                desc:'少于2年',
                score:0
            },{
                desc:'2至5年',
                score:1
            },{
                desc:'5至8年',
                score:2
            },{
                desc:'8年以上',
                score:3
            }
        ]
    },{
        No:8,
        describe:'您对互金行业知识',
        belong:{
            type:2,
            desc:'互金行业知识',
        },
        options:[
            {
                desc:'缺乏投资基本常识',
                score:0
            },{
                desc:'略有了解，但不懂投资技巧',
                score:1
            },{
                desc:'有一定了解，懂一些的投资技巧',
                score:2
            },{
                desc:'认识充分，并懂得投资技巧',
                score:3
            }
        ]
    },{
        No:9,
        describe:'您认为的互金平台应该是',
        belong:{
            type:2,
            desc:'互金行业知识',
        },
        options:[
            {
                desc:'可吸储可放贷',
                score:0
            },{
                desc:'可吸储不可放贷',
                score:1
            },{
                desc:'可放贷不可吸储',
                score:2
            },{
                desc:'信息中介，不可吸储不可放贷',
                score:3
            }
        ]
    },{
        No:10,
        describe:'您的认为的投资理财产品是',
        belong:{
            type:2,
            desc:'互金行业知识',
        },
        options:[
            {
                desc:'无风险',
                score:0
            },{
                desc:'本金是安全的，收益不稳定',
                score:1
            },{
                desc:'本金可能出现少量损失',
                score:2
            },{
                desc:'可能出现大幅亏损，应仔细选择',
                score:3
            }
        ]
    },{
        No:11,
        describe:'以下情况，您会选择哪一种',
        belong:{
            type:3,
            desc:'投资风格',
        },
        options:[
            {
                desc:'有100%的机会赢取1000元现金',
                score:0
            },{
                desc:'有50%的机会赢取5万元现金',
                score:1
            },{
                desc:'有25%的机会赢取50万元现金',
                score:2
            },{
                desc:'有10%的机会赢取100万元现金',
                score:3
            }
        ]
    },{
        No:12,
        describe:'以下哪项描述最符合您的投资态度？',
        belong:{
            type:3,
            desc:'投资风格',
        },
        options:[
            {
                desc:'厌恶风险，不希望本金损失，希望获得稳定回报',
                score:0
            },{
                desc:'保守投资，不希望本金损失，愿意承担一定幅度的收益波动',
                score:1
            },{
                desc:'寻求资金的较高收益和成长性，愿意为此承担有限本金损失',
                score:2
            },{
                desc:'希望赚取高回报，愿意为此承担较大本金损失',
                score:3
            }
        ]
    },{
        No:13,
        describe:'您计划的投资期限是多久',
        belong:{
            type:3,
            desc:'投资风格',
        },
        options:[
            {
                desc:'3个月',
                score:0
            },{
                desc:'6个月',
                score:1
            },{
                desc:'1年',
                score:2
            },{
                desc:'1年以上',
                score:3
            }
        ]
    },{
        No:14,
        describe:'您进行投资的主要目的是',
        belong:{
            type:3,
            desc:'投资风格',
        },
        options:[
            {
                desc:'确保资产的安全性，同时获得固定收益',
                score:0
            },{
                desc:'希望投资能获得一定的增值，同时获得波动适度的回报',
                score:1
            },{
                desc:'倾向于长期的成长，较少关心短期的回报和波动',
                score:2
            },{
                desc:'只关心长期的高回报，能够接受短期的资产价值波动',
                score:3
            }
        ]
    },{
        No:15,
        describe:'您投资产品的价值出现何种程度的波动时，您会呈现明显的焦虑',
        belong:{
            type:4,
            desc:'风险承受能力',
        },
        options:[
            {
                desc:'本金无损失，但收益未达预期',
                score:0
            },{
                desc:'出现轻微本金损失',
                score:1
            },{
                desc:'本金10％以内的损失',
                score:2
            },{
                desc:'本金20-50％的损失',
                score:3
            },{
                desc:'本金50％以上损失',
                score:4
            }
        ]
    }
];


exports.Collection = Collection;

