var winnerInfoList = [
    {"loginName":"zj******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"Mj******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"sa******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"17******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"16******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"13******","virtualPrize":"1.2%加息券","winnerType":"exchange"},
    {"loginName":"ad******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"M1******","virtualPrize":"50","winnerType":"virtual"},
    {"loginName":"Fo******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"cc******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"li******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"gu******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"Jo******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"13******","virtualPrize":"1.2%加息券","winnerType":"exchange"},
    {"loginName":"18******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"M1******","virtualPrize":"50","winnerType":"virtual"},
    {"loginName":"Ji******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"qy******","prizeOne":"1","winnerType":"entity"},
    {"loginName":"Wo******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"Pi******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"M1******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"18******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"13******","virtualPrize":"50","winnerType":"virtual"},
    {"loginName":"17******","virtualPrize":"1.2%加息券","winnerType":"exchange"},
    {"loginName":"cw******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"ki******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"tg******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"dh******","virtualPrize":"5","winnerType":"virtual"},
    {"loginName":"oo******","virtualPrize":"10","winnerType":"virtual"},
    {"loginName":"ga******","virtualPrize":"50","winnerType":"virtual"}]

    module.exports = winnerInfoList;